name: Docker

on:
  pull_request:
    branches: [ main ]

jobs:
  kinto-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./kinto-build
          file: ./Dockerfile
          push: false
          tags: kintohub/kinto-builder:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  kinto-workflow-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./images/kinto-cli
          file: ./Dockerfile
          push: false
          tags: kintohub/kinto-workflow-cli:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  kinto-workflow-main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./images
          file: ./Dockerfile
          push: false
          tags: kintohub/kinto-workflow-main:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}