name: Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  kinto-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: kinto-build
          file: kinto-build/Dockerfile
          push: true
          tags: kintohub/kinto-builder:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  kinto-workflow-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: images/kinto-cli
          file: images/kinto-cli/Dockerfile
          push: true
          tags: kintohub/kinto-workflow-cli:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  kinto-workflow-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: images
          file: images/Dockerfile
          push: true
          tags: kintohub/kinto-workflow-main:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}